### ISSUE TITLE
Example is using outdated api

### ISSUE THREAD

**Issue by thlorenz** [juliangruber/multilevel-chat#1]
[pipe has been deprecated](https://github.com/juliangruber/multilevel-chat/blob/0153e42a8d4fd9239ad78fde7cc3fbbaeaae2130/finished/client.js#L12)

You could probably replace the entire example with your [nodedonfeu demo](https://github.com/juliangruber/nodeconfeu-13/blob/master/done/browser.js).

**Comment by juliangruber** [comment]
thanks, pointed out in the readme
